- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - IdrisIncorporated
  weight: 10
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  # Delta V - fuck all of this HoP is a service role
  # Arcadis - fuck all of this HoP is second to captain
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security # NoooOoOo!! My HoPcurity!1 #too bad it going to reexisted
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
  - Lawyer
  - Cargo
  - Boxer
  - Clown
  - Library
  - Mime
  - Musician
  - Reporter
  - Zookeeper
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: HoPGear
  subGear:
  - HoPPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpack
    shoes: ClothingShoesLeather
    id: HoPPDA
    ears: ClothingHeadsetHoP
  storage:
    back:
    - Flash

- type: startingGear
  id: HoPPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoP
    head: ClothingHeadEnvirohelmHoP
    gloves: ClothingHandsGlovesEnviroglovesHoP
